#!/usr/bin/env bash
# This script displays information about a domain's subdomains and their DNS records.

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"
    local fqdn="${subdomain}.${domain}"
    
    dig +short "$fqdn" | while read -r record; do
        if [[ $record =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "The subdomain ${subdomain} is an A record and points to ${record}"
        else
            echo "The subdomain ${subdomain} is a CNAME record and points to ${record}"
        fi
    done
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
fi
