#!/bin/bash

# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

# Configure nginx to listen on port 80
sed -i 's/^\(listen\s\+\)\([0-9]\+\)\(;.*\)$/\180\3/' /etc/nginx/sites-available/default

# Restart nginx without systemctl
/etc/init.d/nginx reload

# HTML file creation with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
