#!/usr/bin/env bash
customizing a 404-error_page

# Packages updating before installations
sudo apt-get update
sudo apt-get install -y nginx

# An index.html page development
echo "Hello World!" | sudo tee /var/www/html/index.html

# A "moved permanently redirection" (301) performance
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/lucyouma permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# A 404 Custom error page development
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# An HTTP response header developement
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Configuration testing for syntax errors
sudo nginx -t

# Nginx restart after changes implementation
sudo service nginx restart
