#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the nginx configuration file
# and then enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
# terminates the first nginx process 10
kill "$(pgrep 'nginx' | head -1)"
